languages:
  - JavaScript: true
engines:
  eslint:
    enabled: true
    checks:
      comma-dangle:
        enabled: false
      wrap-iife:
        enabled: false
      global-require:
        enabled: false
ratings:
  paths:
    - "**.js"
exclude_paths:
  - "test/**"
