language: node_js
node_js:
  - "4.1"
before_script:
  - npm install -g bower grunt-cli
  - bower install
  - npm install grunt-karma-coveralls
after_success:
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
